name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: dependencies
      run: |
        sudo apt update
        sudo apt-get install freeglut3-dev libglew-dev libdevil-dev
    - name: configure
      run: bash build.sh
